{{- /*
Copyright (c) 2025 SUSE LLC All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Files.Glob "scripts/*" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pytorch.fullname" . }}
  labels:
    {{- include "pytorch.labels" . | nindent 4 }}
data:
{{ ( .Files.Glob "scripts/*" ).AsConfig | indent 2 }}
{{ end }}
